shotaroblog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.DiaryList.as_view(), name='list'),
    path('search/', views.DiarySearchList.as_view(), name='search'),
    path('archive/<int:year>/', views.DiaryYearList.as_view(), name='year'),
    path('archive/<int:year>/<int:month>/', views.DiaryMonthList.as_view(), name='month'),
    path('category/<int:pk>/', views.DiaryCategoryList.as_view(), name='category'),
    path('detail/<int:pk>/', views.DiaryDetail.as_view(), name='detail'),
    path('upload/', views.upload, name='upload'),
]

shotaroblog/shotaroblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
]

shotaroblog/blog/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    
    name = models.CharField('タイトル', max_length=255)

    def __str__(self):
        return self.name


class DiaryQuerySet(models.QuerySet):

    def published(self):
        return self.filter(created_at__lte=timezone.now())


class Diary(models.Model):
    
    title = models.CharField('タイトル', max_length=32)
    text = models.TextField('本文')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='カテゴリ')
    created_at = models.DateTimeField('作成日', default=timezone.now)

    objects = DiaryQuerySet.as_manager()

    def __str__(self):
        return self.title

shotaroblog/blog/forms.py
from django import forms
from django.core.files.storage import default_storage


class DiarySearchForm(forms.Form):
    
    key_word = forms.CharField(
        label='検索キーワード',
        required=False,
    )


class FileUploadForm(forms.Form):
    
    file = forms.FileField()

    def save(self):
        upload_file = self.cleaned_data['file']
        file_name = default_storage.save(upload_file.name, upload_file)
        file_url = default_storage.url(file_name)
        return file_url

shotaroblog/blog/views.py
from django.db.models import Q
from django.http import Http404, HttpResponseBadRequest, JsonResponse
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views import generic
from .forms import DiarySearchForm, FileUploadForm
from .models import Diary, Category


class DiaryMixin:
    model = Diary
    paginate_by = 12
    date_field = 'created_at'
    template_name = 'blog/diary_list.html'
    allow_empty = True
    make_object_list = True


class DiaryList(DiaryMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        return super().get_queryset().select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = 'にっき'
        return context


class DiarySearchList(DiaryMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        queryset = super().get_queryset()
        self.request.form = form = DiarySearchForm(self.request.GET)
        form.is_valid()
        self.key_word = key_word = form.cleaned_data['key_word']
        if key_word:
            queryset = queryset.filter(Q(title__icontains=key_word) | Q(text__icontains=key_word))
        return queryset.select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '「{}」 の検索結果'.format(self.key_word)
        return context


class DiaryCategoryList(DiaryMixin, generic.ArchiveIndexView):

    def get_queryset(self):
        self.category = category = get_object_or_404(Category, pk=self.kwargs['pk'])
        return super().get_queryset().filter(category=category).select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '「{}」 カテゴリのにっき'.format(self.category.name)
        return context


class DiaryYearList(DiaryMixin, generic.YearArchiveView):

    def get_queryset(self):
        return super().get_queryset().select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '{}年のにっき'.format(self.kwargs['year'])
        return context


class DiaryMonthList(DiaryMixin, generic.MonthArchiveView):
    month_format = '%m'

    def get_queryset(self):
        return super().get_queryset().select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['heading'] = '{}年{}月のにっき'.format(self.kwargs['year'], self.kwargs['month'])
        return context


class DiaryDetail(generic.DetailView):
    model = Diary

    def get_object(self, queryset=None):
        diary = super().get_object()
        if diary.created_at <= timezone.now():
            return diary
        raise Http404


def upload(request):
    
    form = FileUploadForm(files=request.FILES)
    if form.is_valid():
        path = form.save()
        url = '{0}://{1}{2}'.format(
            request.scheme,
            request.get_host(),
            path,
        )
        return JsonResponse({'url': url})
    return HttpResponseBadRequest()

shotaroblog/blog/templates/blog/base.html
{% load static %}
{% load blog %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>{% block meta_title %}{% endblock %}</title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:300&display=swap" rel="stylesheet">
    {% block extrahead %}{% endblock %}
</head>
<body>

<header id="site-header">
    <a href="{% url 'blog:list' %}">
        <img src="{% static 'blog/flask.svg' %}" id="hero">
        <p id="title">{% block title %}{% endblock %}</p>
        <p id="subtitle">{% block subtitle %}{% endblock %}</p>
    </a>
</header>

{% block content %}{% endblock %}

<footer id="site-footer">
    <div class="container" id="footer-container">
        {% render_month_links %}

        {% render_category_links %}

        <ul>
            {% block link %}{% endblock %}
        </ul>

        {% render_search_form request %}
    </div>
</footer>


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-72333380-3"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-72333380-3');
</script>
</body>
</html>

shotaroblog/blog/templates/blog/base_site.html
{% extends 'blog/base.html' %}

{% block meta_title %}Shotaroのにっき{% endblock %}
{% block meta_description %}{% endblock %}

{% block title %}Shotaroにっき{% endblock %}
{% block subtitle %}-気まぐれ更新-{% endblock %}

{% block link %}
    <li><a href="https://twitter.com/shotaroscript">Twitter</a></li>
    <li><a href="https://www.instagram.com/726j">インスタ</a></li>
{% endblock %}

shotaroblog/blog/templates/blog/diary_detail.html
{% extends 'blog/base_site.html' %}
{% load blog %}

{% block meta_title %}{{ diary.title }} - {{ block.super }}{% endblock %}
{% block meta_description %}{% endblock %}

{% block content %}
    <section id="diary-detail" class="container">
        <nav class="back"><a href="{% get_return_link request %}">戻る</a></nav>
        <article class="diary">
            <h1 class="diary-title">{{ diary.title }}</h1>
            <p class="meta">
                <time datetime="{{ diary.created_at | date:'Y-m-d' }}">{{ diary.created_at | date:'Y年n月j日' }}</time>
                -
                {{ diary.category }}
            </p>
            <div class="contents text-left">
                {{ diary.text | linebreaks | urlize2 }}
            </div>
        </article>
    </section>
{% endblock %}

shotaroblog/blog/templates/blog/diary_list.html
{% extends 'blog/base_site.html' %}
{% load blog %}

{% block meta_title %}{{ heading }} - {{ block.super }}{% endblock %}

{% block content %}
    <section id="diary-list" class="container">
        <h1 class="section-title">{{ heading }}</h1>

        {% for diary in object_list %}

            <article class="diary">
                <a href="{% url 'blog:detail' diary.pk %}">
                    <h2 class="diary-title">{{ diary.title }}</h2>
                    <p class="meta">
                        <time datetime="{{ diary.created_at | date:'Y-m-d' }}">{{ diary.created_at | date:'Y年n月j日' }}</time>
                        -
                        {{ diary.category }}
                    </p>
                    <div class="contents">
                        <p>
                            {{ diary.text | truncatechars:100 }}
                        </p>
                    </div>
                </a>
            </article>

        {% empty %}
            <p>記事が見つかりませんでした。</p>
        {% endfor %}

        <nav id="page">
            <!-- 1つ前 の部分 -->
            {% if page_obj.has_previous %}
                <a id="prev" href="?{% url_replace request 'page' page_obj.previous_page_number %}"
                   title="前ページへ">前ページ</a>
            {% endif %}

            <span id="page-info">{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span>

            <!-- 1つ後 の部分 -->
            {% if page_obj.has_next %}
                <a id="next" href="?{% url_replace request 'page' page_obj.next_page_number %}" title="次ページへ">次ページ</a>
            {% endif %}
        </nav>

    </section>

{% endblock %}

shotaroblog/blog/templates/blog/includes/category_links.html
<ul>
    {% for category in category_list %}
        <li><a href="{% url 'blog:category' category.pk %}">{{ category }}({{ category.diary_count }})</a></li>
    {% endfor %}
</ul>

shotaroblog/blog/templates/blog/includes/month_links.html
{% regroup dates by year as dates_by_year %}
<ul>
    {% for month in dates_by_year %}
        <li><a href="{% url 'blog:year' month.grouper %}">{{ month.grouper }}年</a>
            <ul>
                {% for d in month.list %}
                    <li><a href="{% url 'blog:month' month.grouper d.month %}">{{ d|date:'F' }}</a></li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
</ul>

shotaroblog/blog/templates/blog/includes/search_form.html
<form action="{% url 'blog:search' %}" method="GET">
    <div class="field">
        {{ search_form.key_word }}
        <button type="submit" id="search" class="search-btn"></button>
    </div>
</form>